function random_stimulu = sample_character(characters, ...
                                            letter_cases, ...
                                            positions, ...
                                            fonts, ...
                                            params)
    random_stimulu = cell(1, 5);
    char_random = randperm(length(characters));char_random = characters(char_random(1));
    case_random = randperm(length(letter_cases));case_random = letter_cases(case_random(1));
    position_random = randperm(length(positions));position_random = positions(position_random(1));
    font_random = randperm(length(fonts));font_random = fonts(font_random(1));
    random_stimulu{1, 1} = char_random{1};
    random_stimulu{1, 2} = case_random{1};
    random_stimulu{1, 3} = position_random{1};
    random_stimulu{1, 4} = font_random{1};
    fn = fullfile(params.path2images, ...
          [char_random{1}, '_', ...
          position_random{1}, '_', ...
          font_random{1}, '_', ...
          case_random{1}, '.png']);
    random_stimulu{1, 5} = imread(fn);
    
end

